name: tiktok
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # getx 路由 + 状态管理 + 多语言 + 主题
  get: ^4.7.2
  # 屏幕适配
  flutter_screenutil: ^5.9.3
  # http 通讯
  dio: ^5.7.0
  # 轮播图
  carousel_slider: ^5.1.1
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  # 日期格式
  intl: ^0.20.2
  # loading提示框
  flutter_easyloading: ^3.0.5
  # 本地存储
  shared_preferences: ^2.5.3
  # 包信息
  package_info_plus: ^8.3.0
  # 播放器
  video_player: ^2.10.0
  # 播放器
  chewie: ^1.12.1
  # 获取文件路径
  path_provider: ^2.1.5
  # 图片缓存管理
  cached_network_image: ^3.4.1
  # 图片预览
  photo_view: ^0.15.0
  # 图片压缩 https://github.com/CocoaPods/CocoaPods/issues/10287
  flutter_image_compress: ^2.4.0
  # permission 权限
  permission_handler: ^12.0.1
  # 获取设备旋转信息
  native_device_orientation: ^2.0.3
  # 保存文件或图片到本地
  image_gallery_saver_plus: ^4.0.1
  # 仿微信 - 媒体选择
  wechat_assets_picker: ^9.5.1
  wechat_camera_picker: ^4.3.7
  # svg
  vector_graphics: ^1.1.19
  # badges 标记
  badges: ^3.1.2
  # 时间选择器
  flutter_datetime_picker_plus: ^2.2.0
  # 滑动列表
  flutter_slidable: ^4.0.0
  # 视频发布
  camerawesome: ^2.5.0
  # 本地身份认证
  local_auth: ^2.3.0
  # 震动反馈
  vibration: ^3.1.3
  # 推特点赞效果
  like_button: ^2.1.0
  # 二维码扫描
  qr_code_scanner_plus: ^2.0.10+1
  # 聊天
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  # emoji表情
  emoji_picker_flutter: ^4.3.0
  # 底部键盘弹框
  chat_bottom_container: ^0.4.0
  # 底部弹框
  bottom_sheet: ^4.0.4
  # 音频波形
  audio_waveforms: ^1.3.0
  # 滚动
  scroll_to_index: ^3.0.1
  # 定位
  geolocator: ^12.0.0
  # 加密安全 SHA/MD5/HMAC
  crypto: ^3.0.6
  # 消息推送
  mqtt_client: ^10.10.0
  # 消息传递
  provider: ^6.1.5
  # 版本更新
  url_launcher: ^6.3.2
  # 文件打开插件
  flutter_app_installer: ^1.0.1
  # lottie动画 加载json
  lottie: ^3.1.3
  # 内嵌webview https://inappwebview.dev/
  flutter_inappwebview: ^6.1.5
  # 音视频通话（rtc）
  agora_rtc_engine: ^6.5.2
  # 实时消息（rtm）
  agora_rtm: ^1.5.9
  # 长列表优化
  keframe: ^3.0.0
  # 调试展示fps
  fps_monitor: ^2.0.0
  # 设备信息
  device_info_plus: ^11.5.0
  # 可见度控制
  visibility_detector: ^0.4.0+2
  # 瀑布流布局
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  vector_graphics_compiler: ^1.1.17

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/videos/
  - assets/lotties/
  - assets/comments/

  - path: assets/svg/
    transformers:
      - package: vector_graphics_compiler

  fonts:
  - family: Alias
    fonts:
      - asset: fonts/iconfont.ttf